//! Reviewed numeric move graph. Direction bindings belong to arrival threads, not squares.
//! Missing authored thread references remain blocked; commented commands are excluded.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) enum End {
    Stay,
    Drop,
    Goal,
}
pub(super) struct Node {
    pub name: &'static str,
    pub legs: &'static [u8],
    pub headings: &'static [&'static str],
    pub square: u8,
    pub dark: u8,
    pub next: [Option<usize>; 4],
    pub end: End,
}
pub(super) static BISHOP: &[Node] = &[
    Node {
        name: "bishop_start_thread",
        legs: &[1],
        headings: &["n"],
        square: 1,
        dark: 0,
        next: [Some(1), None, None, None],
        end: End::Stay,
    },
    Node {
        name: "bishop_1_2_thread",
        legs: &[2],
        headings: &["nw"],
        square: 2,
        dark: 0,
        next: [None, Some(3), Some(2), None],
        end: End::Stay,
    },
    Node {
        name: "bishop_2_1_thread",
        legs: &[1],
        headings: &["se"],
        square: 1,
        dark: 0,
        next: [Some(1), None, None, None],
        end: End::Stay,
    },
    Node {
        name: "bishop_2_3_thread",
        legs: &[3],
        headings: &["ne"],
        square: 3,
        dark: 0,
        next: [Some(5), Some(6), None, Some(4)],
        end: End::Stay,
    },
    Node {
        name: "bishop_3_2_thread",
        legs: &[2],
        headings: &["sw"],
        square: 2,
        dark: 0,
        next: [None, Some(3), Some(2), None],
        end: End::Stay,
    },
    Node {
        name: "bishop_3_4_thread",
        legs: &[4],
        headings: &["nw"],
        square: 4,
        dark: 0,
        next: [None, None, None, None],
        end: End::Stay,
    },
    Node {
        name: "bishop_3_5_thread",
        legs: &[5],
        headings: &["ne"],
        square: 5,
        dark: 0,
        next: [Some(8), Some(9), None, Some(7)],
        end: End::Stay,
    },
    Node {
        name: "bishop_5_3_thread",
        legs: &[3],
        headings: &["sw"],
        square: 3,
        dark: 0,
        next: [Some(5), Some(6), None, Some(4)],
        end: End::Stay,
    },
    Node {
        name: "bishop_5_10_thread",
        legs: &[10],
        headings: &["nw"],
        square: 10,
        dark: 0,
        next: [Some(14), Some(15), Some(13), Some(12)],
        end: End::Stay,
    },
    Node {
        name: "bishop_5_11_thread",
        legs: &[11],
        headings: &["ne"],
        square: 11,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "bishop_7_12_thread",
        legs: &[12],
        headings: &["nw"],
        square: 12,
        dark: 0,
        next: [Some(18), Some(19), Some(17), Some(16)],
        end: End::Stay,
    },
    Node {
        name: "bishop_7_13_thread",
        legs: &[13],
        headings: &["ne"],
        square: 13,
        dark: 0,
        next: [Some(22), Some(23), Some(21), Some(20)],
        end: End::Stay,
    },
    Node {
        name: "bishop_10_4_thread",
        legs: &[4],
        headings: &["sw"],
        square: 4,
        dark: 0,
        next: [None, None, None, None],
        end: End::Stay,
    },
    Node {
        name: "bishop_10_5_thread",
        legs: &[5],
        headings: &["se"],
        square: 5,
        dark: 0,
        next: [Some(8), Some(9), None, Some(7)],
        end: End::Stay,
    },
    Node {
        name: "bishop_10_14_thread",
        legs: &[14],
        headings: &["nw"],
        square: 14,
        dark: 0,
        next: [Some(26), Some(27), Some(25), Some(24)],
        end: End::Stay,
    },
    Node {
        name: "bishop_10_15_thread",
        legs: &[15],
        headings: &["ne"],
        square: 15,
        dark: 0,
        next: [Some(30), Some(31), Some(29), Some(28)],
        end: End::Stay,
    },
    Node {
        name: "bishop_12_6_thread",
        legs: &[6],
        headings: &["sw"],
        square: 6,
        dark: 0,
        next: [None, None, None, None],
        end: End::Stay,
    },
    Node {
        name: "bishop_12_7_thread",
        legs: &[7],
        headings: &["se"],
        square: 7,
        dark: 0,
        next: [Some(10), Some(11), None, None],
        end: End::Stay,
    },
    Node {
        name: "bishop_12_16_thread",
        legs: &[16],
        headings: &["nw"],
        square: 16,
        dark: 0,
        next: [Some(34), Some(35), Some(33), Some(32)],
        end: End::Stay,
    },
    Node {
        name: "bishop_12_17_thread",
        legs: &[17],
        headings: &["ne"],
        square: 17,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "bishop_13_7_thread",
        legs: &[7],
        headings: &["sw"],
        square: 7,
        dark: 0,
        next: [Some(10), Some(11), None, None],
        end: End::Stay,
    },
    Node {
        name: "bishop_13_8_thread",
        legs: &[8],
        headings: &["se"],
        square: 8,
        dark: 0,
        next: [None, None, None, None],
        end: End::Stay,
    },
    Node {
        name: "bishop_13_17_thread",
        legs: &[17],
        headings: &["nw"],
        square: 17,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "bishop_13_18_thread",
        legs: &[18],
        headings: &["ne"],
        square: 18,
        dark: 0,
        next: [Some(37), None, None, Some(36)],
        end: End::Stay,
    },
    Node {
        name: "bishop_14_9_thread",
        legs: &[9],
        headings: &["sw"],
        square: 9,
        dark: 0,
        next: [None, None, None, None],
        end: End::Stay,
    },
    Node {
        name: "bishop_14_10_thread",
        legs: &[10],
        headings: &["se"],
        square: 10,
        dark: 0,
        next: [Some(14), Some(15), Some(13), Some(12)],
        end: End::Stay,
    },
    Node {
        name: "bishop_14_19_thread",
        legs: &[19],
        headings: &["nw"],
        square: 19,
        dark: 0,
        next: [None, Some(39), Some(38), None],
        end: End::Stay,
    },
    Node {
        name: "bishop_14_20_thread",
        legs: &[20],
        headings: &["ne"],
        square: 20,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "bishop_15_10_thread",
        legs: &[10],
        headings: &["sw"],
        square: 10,
        dark: 0,
        next: [Some(14), Some(15), Some(13), Some(12)],
        end: End::Stay,
    },
    Node {
        name: "bishop_15_11_thread",
        legs: &[11],
        headings: &["se"],
        square: 11,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "bishop_15_20_thread",
        legs: &[20],
        headings: &["nw"],
        square: 20,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "bishop_15_21_thread",
        legs: &[21],
        headings: &["ne"],
        square: 21,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "bishop_16_11_thread",
        legs: &[11],
        headings: &["sw"],
        square: 11,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "bishop_16_12_thread",
        legs: &[12],
        headings: &["se"],
        square: 12,
        dark: 0,
        next: [Some(18), Some(19), Some(17), Some(16)],
        end: End::Stay,
    },
    Node {
        name: "bishop_16_21_thread",
        legs: &[21],
        headings: &["nw"],
        square: 21,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "bishop_16_22_thread",
        legs: &[22],
        headings: &["ne"],
        square: 22,
        dark: 0,
        next: [Some(42), Some(43), Some(41), Some(40)],
        end: End::Stay,
    },
    Node {
        name: "bishop_18_13_thread",
        legs: &[13],
        headings: &["sw"],
        square: 13,
        dark: 0,
        next: [Some(22), Some(23), Some(21), Some(20)],
        end: End::Stay,
    },
    Node {
        name: "bishop_18_23_thread",
        legs: &[23],
        headings: &["nw"],
        square: 23,
        dark: 0,
        next: [Some(46), Some(47), Some(45), Some(44)],
        end: End::Stay,
    },
    Node {
        name: "bishop_19_14_thread",
        legs: &[14],
        headings: &["se"],
        square: 14,
        dark: 0,
        next: [Some(26), Some(27), Some(25), Some(24)],
        end: End::Stay,
    },
    Node {
        name: "bishop_19_24_thread",
        legs: &[24],
        headings: &["ne"],
        square: 24,
        dark: 0,
        next: [Some(50), Some(51), Some(49), Some(48)],
        end: End::Stay,
    },
    Node {
        name: "bishop_22_16_thread",
        legs: &[16],
        headings: &["sw"],
        square: 16,
        dark: 0,
        next: [Some(34), Some(35), Some(33), Some(32)],
        end: End::Stay,
    },
    Node {
        name: "bishop_22_17_thread",
        legs: &[17],
        headings: &["se"],
        square: 17,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "bishop_22_26_thread",
        legs: &[26],
        headings: &["nw"],
        square: 26,
        dark: 0,
        next: [Some(58), Some(59), Some(57), Some(56)],
        end: End::Stay,
    },
    Node {
        name: "bishop_22_27_thread",
        legs: &[27],
        headings: &["ne"],
        square: 27,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "bishop_23_17_thread",
        legs: &[17],
        headings: &["sw"],
        square: 17,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "bishop_23_18_thread",
        legs: &[18],
        headings: &["se"],
        square: 18,
        dark: 0,
        next: [Some(37), None, None, Some(36)],
        end: End::Stay,
    },
    Node {
        name: "bishop_23_27_thread",
        legs: &[27],
        headings: &["nw"],
        square: 27,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "bishop_23_28_thread",
        legs: &[28],
        headings: &["ne"],
        square: 28,
        dark: 0,
        next: [Some(61), Some(62), None, Some(60)],
        end: End::Stay,
    },
    Node {
        name: "bishop_24_19_thread",
        legs: &[19],
        headings: &["sw"],
        square: 19,
        dark: 0,
        next: [None, Some(39), Some(38), None],
        end: End::Stay,
    },
    Node {
        name: "bishop_24_20_thread",
        legs: &[20],
        headings: &["se"],
        square: 20,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "bishop_24_29_thread",
        legs: &[29],
        headings: &["nw"],
        square: 29,
        dark: 0,
        next: [None, None, None, None],
        end: End::Stay,
    },
    Node {
        name: "bishop_24_30_thread",
        legs: &[30],
        headings: &["ne"],
        square: 30,
        dark: 0,
        next: [None, None, Some(64), Some(63)],
        end: End::Stay,
    },
    Node {
        name: "bishop_25_20_thread",
        legs: &[20],
        headings: &["sw"],
        square: 20,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "bishop_25_21_thread",
        legs: &[21],
        headings: &["se"],
        square: 21,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "bishop_25_30_thread",
        legs: &[30],
        headings: &["nw"],
        square: 30,
        dark: 0,
        next: [None, None, Some(64), Some(63)],
        end: End::Stay,
    },
    Node {
        name: "bishop_25_31_thread",
        legs: &[31],
        headings: &["ne"],
        square: 31,
        dark: 0,
        next: [None, None, Some(66), Some(65)],
        end: End::Stay,
    },
    Node {
        name: "bishop_26_21_thread",
        legs: &[21],
        headings: &["sw"],
        square: 21,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "bishop_26_22_thread",
        legs: &[22],
        headings: &["se"],
        square: 22,
        dark: 0,
        next: [Some(42), Some(43), Some(41), Some(40)],
        end: End::Stay,
    },
    Node {
        name: "bishop_26_31_thread",
        legs: &[31],
        headings: &["nw"],
        square: 31,
        dark: 0,
        next: [None, None, Some(66), Some(65)],
        end: End::Stay,
    },
    Node {
        name: "bishop_26_32_thread",
        legs: &[32],
        headings: &["ne"],
        square: 32,
        dark: 0,
        next: [None, None, Some(68), Some(67)],
        end: End::Stay,
    },
    Node {
        name: "bishop_28_23_thread",
        legs: &[23],
        headings: &["sw"],
        square: 23,
        dark: 0,
        next: [Some(46), Some(47), Some(45), Some(44)],
        end: End::Stay,
    },
    Node {
        name: "bishop_28_33_thread",
        legs: &[33],
        headings: &["nw"],
        square: 33,
        dark: 0,
        next: [None, None, Some(70), Some(69)],
        end: End::Stay,
    },
    Node {
        name: "bishop_28_34_thread",
        legs: &[34],
        headings: &["ne"],
        square: 34,
        dark: 0,
        next: [None, None, None, None],
        end: End::Goal,
    },
    Node {
        name: "bishop_30_24_thread",
        legs: &[24],
        headings: &["sw"],
        square: 24,
        dark: 0,
        next: [Some(50), Some(51), Some(49), Some(48)],
        end: End::Stay,
    },
    Node {
        name: "bishop_30_25_thread",
        legs: &[25],
        headings: &["se"],
        square: 25,
        dark: 0,
        next: [Some(54), Some(55), Some(53), Some(52)],
        end: End::Stay,
    },
    Node {
        name: "bishop_31_25_thread",
        legs: &[25],
        headings: &["sw"],
        square: 25,
        dark: 0,
        next: [Some(54), Some(55), Some(53), Some(52)],
        end: End::Stay,
    },
    Node {
        name: "bishop_31_26_thread",
        legs: &[26],
        headings: &["se"],
        square: 26,
        dark: 0,
        next: [Some(58), Some(59), Some(57), Some(56)],
        end: End::Stay,
    },
    Node {
        name: "bishop_32_26_thread",
        legs: &[26],
        headings: &["sw"],
        square: 26,
        dark: 0,
        next: [Some(58), Some(59), Some(57), Some(56)],
        end: End::Stay,
    },
    Node {
        name: "bishop_32_27_thread",
        legs: &[27],
        headings: &["se"],
        square: 27,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "bishop_33_27_thread",
        legs: &[27],
        headings: &["sw"],
        square: 27,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "bishop_33_28_thread",
        legs: &[28],
        headings: &["se"],
        square: 28,
        dark: 0,
        next: [Some(61), Some(62), None, Some(60)],
        end: End::Stay,
    },
];

pub(super) static KNIGHT: &[Node] = &[
    Node {
        name: "knight_start_thread",
        legs: &[9],
        headings: &["w"],
        square: 9,
        dark: 0,
        next: [None, None, None, Some(19)],
        end: End::Stay,
    },
    Node {
        name: "knight_2_4_thread",
        legs: &[1, 4],
        headings: &["w", "m"],
        square: 4,
        dark: 7,
        next: [Some(9), Some(8), Some(7), None],
        end: End::Stay,
    },
    Node {
        name: "knight_2_5_thread",
        legs: &[5],
        headings: &["n"],
        square: 5,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "knight_2_11_thread",
        legs: &[1, 11],
        headings: &["w", "n"],
        square: 11,
        dark: 0,
        next: [Some(23), Some(21), None, None],
        end: End::Stay,
    },
    Node {
        name: "knight_2_13_thread",
        legs: &[3, 13],
        headings: &["e", "n"],
        square: 13,
        dark: 0,
        next: [Some(28), None, Some(25), Some(26)],
        end: End::Stay,
    },
    Node {
        name: "knight_3_2_thread",
        legs: &[2],
        headings: &["w"],
        square: 2,
        dark: 9,
        next: [Some(2), None, None, Some(1)],
        end: End::Stay,
    },
    Node {
        name: "knight_3_6_thread",
        legs: &[6],
        headings: &["n"],
        square: 6,
        dark: 11,
        next: [Some(15), Some(13), None, Some(12)],
        end: End::Stay,
    },
    Node {
        name: "knight_4_3_thread",
        legs: &[1, 3],
        headings: &["s", "e"],
        square: 3,
        dark: 0,
        next: [Some(6), None, None, Some(5)],
        end: End::Stay,
    },
    Node {
        name: "knight_4_5_thread",
        legs: &[5],
        headings: &["e"],
        square: 5,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "knight_4_11_thread",
        legs: &[11],
        headings: &["n"],
        square: 11,
        dark: 0,
        next: [Some(23), Some(21), None, None],
        end: End::Stay,
    },
    Node {
        name: "knight_6_2_thread",
        legs: &[2],
        headings: &["s"],
        square: 2,
        dark: 11,
        next: [Some(2), Some(4), None, Some(3)],
        end: End::Stay,
    },
    Node {
        name: "knight_6_3_thread",
        legs: &[3],
        headings: &["s"],
        square: 3,
        dark: 0,
        next: [Some(6), None, None, Some(5)],
        end: End::Stay,
    },
    Node {
        name: "knight_6_4_thread",
        legs: &[5],
        headings: &["w"],
        square: 5,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "knight_6_8_thread",
        legs: &[8],
        headings: &["e"],
        square: 8,
        dark: 8,
        next: [None, None, None, Some(18)],
        end: End::Stay,
    },
    Node {
        name: "knight_6_13_thread",
        legs: &[13],
        headings: &["n"],
        square: 13,
        dark: 0,
        next: [Some(28), None, Some(25), Some(26)],
        end: End::Stay,
    },
    Node {
        name: "knight_6_13b_thread",
        legs: &[13],
        headings: &["n"],
        square: 13,
        dark: 0,
        next: [None, Some(27), None, Some(26)],
        end: End::Stay,
    },
    Node {
        name: "knight_7_5_thread",
        legs: &[5],
        headings: &["w"],
        square: 5,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "knight_7_9_thread",
        legs: &[9],
        headings: &["e"],
        square: 9,
        dark: 0,
        next: [None, None, None, Some(19)],
        end: End::Stay,
    },
    Node {
        name: "knight_8_6_thread",
        legs: &[6],
        headings: &["w"],
        square: 6,
        dark: 5,
        next: [Some(14), None, Some(11), None],
        end: End::Stay,
    },
    Node {
        name: "knight_9_14_thread",
        legs: &[14],
        headings: &["w"],
        square: 14,
        dark: 12,
        next: [None, None, Some(29), Some(30)],
        end: End::Stay,
    },
    Node {
        name: "knight_11_5_thread",
        legs: &[4, 5],
        headings: &["s", "e"],
        square: 5,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "knight_11_12_thread",
        legs: &[12],
        headings: &["e"],
        square: 12,
        dark: 0,
        next: [None, None, None, None],
        end: End::Stay,
    },
    Node {
        name: "knight_11_13_thread",
        legs: &[12],
        headings: &["e"],
        square: 10,
        dark: 0,
        next: [None, None, None, None],
        end: End::Stay,
    },
    Node {
        name: "knight_11_16_thread",
        legs: &[16],
        headings: &["n"],
        square: 16,
        dark: 10,
        next: [None, Some(37), None, Some(36)],
        end: End::Stay,
    },
    Node {
        name: "knight_13_3_thread",
        legs: &[3],
        headings: &["s"],
        square: 3,
        dark: 0,
        next: [Some(6), None, None, Some(5)],
        end: End::Stay,
    },
    Node {
        name: "knight_13_6_thread",
        legs: &[6],
        headings: &["s"],
        square: 6,
        dark: 14,
        next: [None, Some(13), Some(10), Some(12)],
        end: End::Stay,
    },
    Node {
        name: "knight_13_12_thread",
        legs: &[12],
        headings: &["w"],
        square: 12,
        dark: 0,
        next: [None, None, None, None],
        end: End::Stay,
    },
    Node {
        name: "knight_13_14_thread",
        legs: &[14],
        headings: &["e"],
        square: 14,
        dark: 12,
        next: [None, None, Some(29), Some(30)],
        end: End::Stay,
    },
    Node {
        name: "knight_13_18_thread",
        legs: &[18],
        headings: &["n"],
        square: 18,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "knight_14_7_thread",
        legs: &[7],
        headings: &["s"],
        square: 7,
        dark: 0,
        next: [None, Some(17), None, Some(16)],
        end: End::Stay,
    },
    Node {
        name: "knight_14_13_thread",
        legs: &[13],
        headings: &["w"],
        square: 13,
        dark: 0,
        next: [Some(28), None, Some(24), Some(26)],
        end: End::Stay,
    },
    Node {
        name: "knight_15_10_thread",
        legs: &[10],
        headings: &["s"],
        square: 10,
        dark: 0,
        next: [None, None, None, None],
        end: End::Stay,
    },
    Node {
        name: "knight_15_16_thread",
        legs: &[16],
        headings: &["e"],
        square: 16,
        dark: 7,
        next: [Some(39), Some(37), Some(34), None],
        end: End::Stay,
    },
    Node {
        name: "knight_15_19_thread",
        legs: &[19],
        headings: &["n"],
        square: 19,
        dark: 0,
        next: [None, None, None, None],
        end: End::Stay,
    },
    Node {
        name: "knight_16_4_thread",
        legs: &[4],
        headings: &["s"],
        square: 4,
        dark: 7,
        next: [Some(9), Some(8), Some(7), None],
        end: End::Stay,
    },
    Node {
        name: "knight_16_11_thread",
        legs: &[11],
        headings: &["s"],
        square: 11,
        dark: 0,
        next: [None, None, Some(22), Some(20)],
        end: End::Stay,
    },
    Node {
        name: "knight_16_15_thread",
        legs: &[15],
        headings: &["w"],
        square: 15,
        dark: 0,
        next: [Some(33), Some(32), Some(31), None],
        end: End::Stay,
    },
    Node {
        name: "knight_16_17_thread",
        legs: &[17],
        headings: &["e"],
        square: 17,
        dark: 0,
        next: [None, None, None, None],
        end: End::Stay,
    },
    Node {
        name: "knight_16_20_thread",
        legs: &[20],
        headings: &["n"],
        square: 20,
        dark: 0,
        next: [Some(42), Some(41), None, None],
        end: End::Stay,
    },
    Node {
        name: "knight_16_24_thread",
        legs: &[24],
        headings: &["n"],
        square: 24,
        dark: 6,
        next: [None, Some(51), Some(50), None],
        end: End::Stay,
    },
    Node {
        name: "knight_20_16_thread",
        legs: &[16],
        headings: &["s"],
        square: 16,
        dark: 10,
        next: [None, Some(37), None, Some(36)],
        end: End::Stay,
    },
    Node {
        name: "knight_20_22_thread",
        legs: &[21],
        headings: &["e"],
        square: 21,
        dark: 0,
        next: [None, None, None, None],
        end: End::Stay,
    },
    Node {
        name: "knight_20_25_thread",
        legs: &[24, 25],
        headings: &["n", "e"],
        square: 25,
        dark: 0,
        next: [None, Some(55), Some(53), Some(52)],
        end: End::Stay,
    },
    Node {
        name: "knight_22_13_thread",
        legs: &[18],
        headings: &["s"],
        square: 18,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "knight_22_18_thread",
        legs: &[18],
        headings: &["s"],
        square: 18,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "knight_22_21_thread",
        legs: &[21],
        headings: &["w"],
        square: 21,
        dark: 0,
        next: [None, None, None, None],
        end: End::Stay,
    },
    Node {
        name: "knight_22_24_thread",
        legs: &[26, 24],
        headings: &["n", "w"],
        square: 24,
        dark: 6,
        next: [None, Some(51), Some(50), None],
        end: End::Stay,
    },
    Node {
        name: "knight_22_28_thread",
        legs: &[23, 28],
        headings: &["e", "n"],
        square: 28,
        dark: 6,
        next: [None, Some(65), Some(64), None],
        end: End::Stay,
    },
    Node {
        name: "knight_23_22_thread",
        legs: &[22],
        headings: &["w"],
        square: 22,
        dark: 12,
        next: [None, None, Some(43), Some(45)],
        end: End::Stay,
    },
    Node {
        name: "knight_23_27_thread",
        legs: &[27],
        headings: &["n"],
        square: 27,
        dark: 0,
        next: [Some(63), None, None, Some(61)],
        end: End::Stay,
    },
    Node {
        name: "knight_24_20_thread",
        legs: &[20],
        headings: &["s"],
        square: 20,
        dark: 0,
        next: [None, Some(41), Some(40), None],
        end: End::Stay,
    },
    Node {
        name: "knight_24_25_thread",
        legs: &[25],
        headings: &["e"],
        square: 25,
        dark: 0,
        next: [None, Some(54), Some(53), None],
        end: End::Stay,
    },
    Node {
        name: "knight_25_16_thread",
        legs: &[24, 16],
        headings: &["w", "s"],
        square: 16,
        dark: 7,
        next: [Some(38), Some(37), Some(35), None],
        end: End::Stay,
    },
    Node {
        name: "knight_25_21_thread",
        legs: &[21],
        headings: &["s"],
        square: 21,
        dark: 0,
        next: [None, None, None, None],
        end: End::Stay,
    },
    Node {
        name: "knight_25_22_thread",
        legs: &[26, 22],
        headings: &["e", "s"],
        square: 22,
        dark: 0,
        next: [Some(46), Some(47), Some(44), Some(45)],
        end: End::Stay,
    },
    Node {
        name: "knight_25_26_thread",
        legs: &[26],
        headings: &["e"],
        square: 26,
        dark: 6,
        next: [None, Some(58), None, None],
        end: End::Stay,
    },
    Node {
        name: "knight_25_27_thread",
        legs: &[27],
        headings: &["e"],
        square: 27,
        dark: 0,
        next: [Some(62), None, Some(59), None],
        end: End::Stay,
    },
    Node {
        name: "knight_26_18_thread",
        legs: &[18],
        headings: &["s"],
        square: 18,
        dark: 0,
        next: [None, None, None, None],
        end: End::Drop,
    },
    Node {
        name: "knight_26_27_thread",
        legs: &[27],
        headings: &["e"],
        square: 27,
        dark: 0,
        next: [Some(62), None, Some(59), None],
        end: End::Stay,
    },
    Node {
        name: "knight_27_23_thread",
        legs: &[23],
        headings: &["s"],
        square: 23,
        dark: 9,
        next: [Some(49), None, None, Some(48)],
        end: End::Stay,
    },
    Node {
        name: "knight_27_22_thread",
        legs: &[23, 22],
        headings: &["s", "w"],
        square: 22,
        dark: 0,
        next: [Some(46), Some(47), Some(44), Some(45)],
        end: End::Stay,
    },
    Node {
        name: "knight_27_25_thread",
        legs: &[25],
        headings: &["w"],
        square: 25,
        dark: 0,
        next: [None, Some(55), Some(53), Some(52)],
        end: End::Stay,
    },
    Node {
        name: "knight_27_28_thread",
        legs: &[28],
        headings: &["n"],
        square: 28,
        dark: 6,
        next: [None, Some(65), Some(64), None],
        end: End::Stay,
    },
    Node {
        name: "knight_27_29_thread",
        legs: &[28, 29],
        headings: &["n", "e"],
        square: 29,
        dark: 0,
        next: [None, None, None, Some(66)],
        end: End::Stay,
    },
    Node {
        name: "knight_28_27_thread",
        legs: &[27],
        headings: &["s"],
        square: 27,
        dark: 0,
        next: [None, None, Some(60), Some(61)],
        end: End::Stay,
    },
    Node {
        name: "knight_28_31_thread",
        legs: &[30, 31],
        headings: &["e", "n"],
        square: 31,
        dark: 0,
        next: [None, None, None, None],
        end: End::Goal,
    },
    Node {
        name: "knight_29_23_thread",
        legs: &[28, 23],
        headings: &["w", "s"],
        square: 23,
        dark: 9,
        next: [Some(49), None, None, Some(48)],
        end: End::Stay,
    },
];
