"""Windows setup integration checks with synthetic PK3 fixtures, no game data."""
from pathlib import Path
import json
import os
import shutil
import struct
import subprocess
import unittest
import uuid
import zipfile

ROOT = Path(__file__).resolve().parents[1]
PACKS = ("pak0.pk3", "pak1_large.pk3", "pak2.pk3", "pak3.pk3", "pak4_english.pk3", "pak5_mod.pk3")
TEST_ROOT = ROOT / "private" / ("setup-tests-" + uuid.uuid4().hex)


def make_data(root, version=42):
    base = root / "Alice1" / "bin" / "base"
    base.mkdir(parents=True)
    for index, name in enumerate(PACKS):
        with zipfile.ZipFile(base / name, "w", zipfile.ZIP_DEFLATED) as pack:
            pack.writestr("synthetic-fixture.txt", "Not original game data")
            if index == 0:
                header = b"FAKK" + struct.pack("<i", version)
                pack.writestr("maps/gvillage.bsp", header)
                for i in range(35):
                    pack.writestr(f"maps/synthetic{i}.bsp", header)
    return base


@unittest.skipUnless(os.name == "nt", "Setup.cmd is a Windows entry point")
class SetupTests(unittest.TestCase):
    def setUp(self):
        self.root = TEST_ROOT / self._testMethodName
        self.app = self.root / "Looking Glass & preview [test]"
        self.app.mkdir(parents=True)
        shutil.copyfile(ROOT / "Setup.cmd", self.app / "Setup.cmd")
        self.data = self.root / "Données & game [test]"
        self.base = make_data(self.data)

    def run_setup(self, source, expected=0):
        # Paths are generated by these fixtures (no quotes/newlines/percent signs).
        # Pass them as literal quoted CMD arguments, never interpolate into PS code.
        command = f'"{os.environ["COMSPEC"]}" /d /s /c ""{self.app / "Setup.cmd"}" "{source}" --no-pause"'
        result = subprocess.run(command, cwd=self.app, capture_output=True, timeout=60)
        self.assertEqual(result.returncode, expected, result.stdout.decode(errors="replace") + result.stderr.decode(errors="replace"))
        return result

    def saved_path(self):
        return (self.app / "private/data-path.txt").read_text(encoding="utf-8").strip()

    def test_folder_with_spaces_unicode_and_metacharacters(self):
        self.run_setup(self.data)
        self.assertEqual(Path(self.saved_path()), self.base)
        receipt = json.loads((self.app / "private/setup.json").read_text(encoding="utf-8"))
        self.assertIsNone(receipt["archiveSha256"])

    def test_failure_preserves_configuration_and_saves(self):
        self.run_setup(self.data)
        before = self.saved_path()
        save = self.app / "private/saves/user-save.txt"
        save.parent.mkdir()
        save.write_text("preserve my save")
        self.run_setup(self.root / "missing.7z", expected=1)
        self.assertEqual(self.saved_path(), before)
        self.assertEqual(save.read_text(), "preserve my save")

    def test_wrong_map_format_is_rejected(self):
        invalid = self.root / "wrong version"
        make_data(invalid, version=41)
        self.run_setup(invalid, expected=1)
        self.assertFalse((self.app / "private/data-path.txt").exists())

    def test_corrupt_pack_is_rejected(self):
        (self.base / "pak3.pk3").write_bytes(b"not a zip")
        self.run_setup(self.data, expected=1)
        self.assertFalse((self.app / "private/data-path.txt").exists())

    def test_relative_location_and_automatic_discovery(self):
        internal = self.app / "alice_202106"
        base = make_data(internal)
        self.run_setup("")
        self.assertEqual(self.saved_path(), str(base.relative_to(self.app)))

    def test_archive_extracts_only_data_and_reuses_import(self):
        extractor = shutil.which("7z") or shutil.which("7zz")
        if not extractor:
            candidate = Path(os.environ.get("ProgramFiles", "C:/Program Files")) / "7-Zip/7z.exe"
            extractor = str(candidate) if candidate.is_file() else None
        if not extractor:
            self.skipTest("7-Zip is needed for the archive extraction case")
        (self.data / "Alice1/bin/original.exe").write_bytes(b"must not be extracted")
        (self.data / "Alice1/bin/base/unwanted.cmd").write_text("must not be extracted")
        archive = self.root / "Alice1_2011_vanilla.7z"
        subprocess.run([extractor, "a", "-t7z", str(archive), "Alice1"], cwd=self.data, check=True, capture_output=True)
        self.run_setup(archive)
        before = self.saved_path()
        imported = self.app / before
        self.assertEqual(sorted(p.name for p in imported.iterdir()), sorted(PACKS))
        self.run_setup(archive)
        self.assertEqual(self.saved_path(), before)
        self.assertEqual(len(list((self.app / "private/game-data").iterdir())), 1)


if __name__ == "__main__":
    print(f"Synthetic setup fixtures stay in the ignored folder: {TEST_ROOT}")
    unittest.main()
